services:
  server:
    build: .
    container_name: bia
    ports:
      - "80:8080"

    depends_on:
      - redis

    environment:
      DB_USER: postgres
      DB_PWD: bYdMdoWPbnVexXmEKm9Z
      DB_HOST: bia.cyhwc2c28vmy.us-east-1.rds.amazonaws.com
      DB_PORT: 5432

  redis:
    image: valkey/valkey:8.1-alpine
    container_name: redis
